# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Jekyll Build and Health Check

on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

  # Allows the health check job to run on a schedule
  schedule:
    - cron: "30 * * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build and deploy job for Jekyll site
  build_and_deploy:
    runs-on: ubuntu-latest
    if: "!github.event.schedule"  # This ensures the job only runs on push, PR, or manual dispatch
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: List _site directory
        run: ls -R ./_site  # Debug step to list contents of the _site directory
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-artifact
          path: ./_site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_and_deploy
    if: "!github.event.schedule"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site-artifact
          path: ./_site
      - name: List downloaded directory
        run: ls -R ./_site  # Debug step to list contents of the _site directory after download
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

  # Health check job
  health_check_job:
    runs-on: ubuntu-latest
    if: github.event.schedule  # This ensures the job only runs on a schedule
    name: Check all sites
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
