name: Scheduled Health Check

on:
  schedule:
    - cron: "30 * * * *"  # Runs every hour at the 30th minute
  workflow_dispatch:

permissions:
  contents: write  # Ensures the GITHUB_TOKEN has write permissions

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Health Check Script
        run: |
          chmod +x ./health-check.sh
          ./health-check.sh
              
      - name: Debug - List Files
        run: ls -al logs
        
      - name: Trigger Deployment Workflow
        uses: ./.github/workflows/build.yml
